name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}       

      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bwhittaker34/whittaker-ceg3120
          tags: |
            type=ref,event=tag
            mode=semver
            prefix=v
            supplementary-latest=true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Project4/Dockerfile  
          push: true
          tags: ${{ steps.meta.outputs.tags }}
